version: 0.0
os: linux
files:
  - source: /
    destination: /home/farnsworth/farnsworth
hooks:
  BeforeInstall:
    - location: deploy_scripts/BeforeInstall.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: deploy_scripts/AfterInstall.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: deploy_scripts/ApplicationStart.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: deploy_scripts/ApplicationStop.sh
      timeout: 300
      runas: root
